version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app/step2/zip/
    overwrite: yes

permissions:
  - object: /home/ubuntu/app/step2/zip/
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: /scripts/deploy.sh
      timeout: 60
      runas: ubuntu