spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${pwd}

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      password : ${encrypt}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    session:
      timeout:
      tracking-modes: cookie
