
name: aboutMatch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash
    
    - name: Build with Gradle
      run: ./gradlew clean build
      shell: bash
      
    - name: Make zip file
      run: zip -r ./deploy.zip .
      shell: bash
      
    - name: Generate deployment package
      run: |
        mkdir -p before-deploy
        cp scripts/*.sh before-deploy/
        cp appspec.yml before-deploy/
        cp build/libs/*.jar before-deploy/
        cd before-deploy && zip -r before-deploy *
        cd ../ && mkdir -p deploy
        mv before-deploy/before-deploy.zip deploy/deploy.zip
      shell: bash
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2
    
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://aboutmatch-build/deploy.zip

    - name: Code Deploy
      run: aws deploy create-deployment --application-name aboutMatch --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name aboutMatch-group --s3-location bucket=aboutmatch-build,bundleType=zip,key=deploy.zip
